# Generated by Django 3.0.4 on 2020-03-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMap',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('phrase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=512)),
                ('No_of_upvote', models.IntegerField()),
                ('room_id', models.ManyToManyField(to='API.AdminMap')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('banned', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.ManyToManyField(to='API.Message')),
                ('room_id', models.ManyToManyField(to='API.AdminMap')),
                ('user_id', models.ManyToManyField(to='API.User')),
            ],
        ),
        migrations.AddField(
            model_name='adminmap',
            name='admin_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.User'),
        ),
    ]
