# Generated by Django 3.0.4 on 2020-03-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banned',
            field=models.TimeField(),
        ),
    ]
